apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
  - host: php-test.divan.ru
  - externalIPs: 10.20.50.50
    http:
      paths:
      - backend:
          serviceName: nginx
          servicePort: 80
